// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Footer': typeof import('../components/Footer.vue')['default'],
    'Header': typeof import('../components/Header.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
